name:                polysemy-video
version:             0.1.3.0
git:                 "https://gitlab.com/homotopic-tech/polysemy-video"
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

category:            video polysemy
description:         Experimental video processing DSL for polysemy.

dependencies:
- base >= 4.7 && < 5
- formatting >= 7.0.0 && < 7.2
- simple-media-timestamp >= 0.2 && < 0.3
- simple-media-timestamp-formatting >= 0.1 && < 0.2
- path >= 0.7 && < 0.10
- path-formatting >= 0.1.0.0 && < 0.2
- polysemy >= 1.3.0.0 && < 1.7
- text
- turtle

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
